version: '3.7'
services:
  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    container_name : minio
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 12345678
      MINIO_SERVER_URL: http://minio:9090
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - /data/oss:/data
      - /data/oss/config:/root/.minio
    command: server /data --console-address ":9000" --address ":9090"

  nginx:
    container_name: nginx-reverse-proxy
    image: nginx:1.25.1
    volumes:
        - /data/projects/scripts/minio/conf:/etc/nginx/conf.d:ro    
    ports:
    - 9091:9091  
    restart: unless-stopped
