import megfile.config  # noqa: F401  # make sure env config is loaded
from megfile.fs_path import FSPath, fs_copy, is_fs
from megfile.hdfs_path import HdfsPath, is_hdfs
from megfile.http_path import HttpPath, HttpsPath, is_http
from megfile.s3_path import (
    S3Path,
    is_s3,
    s3_buffered_open,
    s3_cached_open,
    s3_concat,
    s3_copy,
    s3_download,
    s3_load_content,
    s3_memory_open,
    s3_open,
    s3_pipe_open,
    s3_prefetch_open,
    s3_share_cache_open,
    s3_upload,
)
from megfile.sftp_path import (
    SftpPath,
    is_sftp,
    sftp_add_host_key,
    sftp_concat,
    sftp_copy,
    sftp_download,
    sftp_upload,
)
from megfile.smart import (
    smart_access,
    smart_cache,
    smart_combine_open,
    smart_concat,
    smart_copy,
    smart_exists,
    smart_getmd5,
    smart_getmtime,
    smart_getsize,
    smart_glob,
    smart_glob_stat,
    smart_iglob,
    smart_isdir,
    smart_isfile,
    smart_islink,
    smart_listdir,
    smart_load_content,
    smart_load_from,
    smart_load_text,
    smart_lstat,
    smart_makedirs,
    smart_move,
    smart_open,
    smart_path_join,
    smart_readlink,
    smart_realpath,
    smart_remove,
    smart_rename,
    smart_save_as,
    smart_save_content,
    smart_save_text,
    smart_scan,
    smart_scan_stat,
    smart_scandir,
    smart_stat,
    smart_symlink,
    smart_sync,
    smart_touch,
    smart_unlink,
    smart_walk,
)
from megfile.smart_path import SmartPath
from megfile.stdio_path import StdioPath, is_stdio
from megfile.version import VERSION as __version__  # noqa: F401

try:
    from megfile.sftp2_path import Sftp2Path
except ImportError:
    Sftp2Path = None

try:
    from megfile.webdav_path import WebdavPath, is_webdav
except ImportError:
    WebdavPath = is_webdav = None

__all__ = [
    "smart_access",
    "smart_cache",
    "smart_cache",
    "smart_combine_open",
    "smart_concat",
    "smart_copy",
    "smart_exists",
    "smart_getmd5",
    "smart_getmtime",
    "smart_getsize",
    "smart_glob_stat",
    "smart_glob",
    "smart_iglob",
    "smart_isdir",
    "smart_isfile",
    "smart_islink",
    "smart_listdir",
    "smart_load_content",
    "smart_load_from",
    "smart_load_text",
    "smart_lstat",
    "smart_makedirs",
    "smart_move",
    "smart_open",
    "smart_path_join",
    "smart_readlink",
    "smart_realpath",
    "smart_remove",
    "smart_rename",
    "smart_save_as",
    "smart_save_content",
    "smart_save_text",
    "smart_scan_stat",
    "smart_scan",
    "smart_scandir",
    "smart_stat",
    "smart_symlink",
    "smart_sync",
    "smart_touch",
    "smart_unlink",
    "smart_walk",
    "is_fs",
    "fs_copy",
    "is_hdfs",
    "is_http",
    "is_s3",
    "s3_buffered_open",
    "s3_cached_open",
    "s3_concat",
    "s3_copy",
    "s3_download",
    "s3_load_content",
    "s3_memory_open",
    "s3_open",
    "s3_pipe_open",
    "s3_prefetch_open",
    "s3_share_cache_open",
    "s3_upload",
    "is_sftp",
    "sftp_add_host_key",
    "sftp_concat",
    "sftp_copy",
    "sftp_download",
    "sftp_upload",
    "is_stdio",
    "stdio_open",
    "is_webdav",
    "FSPath",
    "HdfsPath",
    "HttpPath",
    "HttpsPath",
    "S3Path",
    "SftpPath",
    "SmartPath",
    "StdioPath",
    "WebdavPath",
]
