name: Automatic Approve
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  automatic-approve:
    name: Automatic Approve
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Approve
        uses: mheap/automatic-approve-action@v1
        with:
          token: ${{ secrets.PAT }}
          workflows: "run-tests.yml,publish-docs.yml"
          dangerous_files: "requirements.txt,requirements-dev.txt,scripts/convert_results_to_sarif.py"
